# Generated by Django 3.2.10 on 2021-12-15 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=10)),
                ('student_age', models.IntegerField()),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
